spring:
  application:
    name: levain
  profiles:
    active: local
    include: my
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 5MB
      enabled: true

server:
  port: 8090